#!/usr/bin/env bash
# Script to build ZynthianOS
# The start Script for this module
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

set -x
alias bash='bash -x'

function systemctl() {
	echo "systemctl trutxo!"
}

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

# Set dpkg interface
export DEBIAN_FRONTEND=noninteractive

#------------------------------------------------------------------------------
# Get System Codebase
#------------------------------------------------------------------------------

ZYNTHIAN_OS_CODEBASE=`lsb_release -cs`

#------------------------------------------------------------------------------
# Load Environment Variables
#------------------------------------------------------------------------------

source "/zynthian/config/zynthian_envars.sh"

#------------------------------------------------------------------------------
# Pull from zynthian-sys repotory ...
#------------------------------------------------------------------------------

echo "Updating zynthian-sys ..."
cd $ZYNTHIAN_SYS_DIR
git checkout .
git pull

#------------------------------------------------------------------------------
# Call update subscripts ...
#------------------------------------------------------------------------------

echo "UPDATING ZYNTHIAN ..."
cd ./scripts
./update_zynthian_recipes.sh
./update_zynthian_data.sh
./update_zynthian_sys.sh
./update_zynthian_code.sh

#------------------------------------------------------------------------------
# Update System ...
#------------------------------------------------------------------------------

apt-get -y update
apt-get -y upgrade

#------------------------------------------------------------------------------
# Adjustments ...
#------------------------------------------------------------------------------

# Copy the plugins configuration that is strangely lost
cp "$ZYNTHIAN_SYS_DIR/config/default_jalv_plugins.json" "/zynthian/config/jalv/plugins.json"

# Copy default snapshots
cp -a $ZYNTHIAN_DATA_DIR/snapshots/* $ZYNTHIAN_MY_DATA_DIR/snapshots/000

# Copy MIDI examples
cp -a $ZYNTHIAN_DATA_DIR/mid/*.mid $ZYNTHIAN_MY_DATA_DIR/capture


#------------------------------------------------------------------------------
# Update TimeStamp, clean everything and ends...
#------------------------------------------------------------------------------

# Update Build Info TimeStamp
TIMESTAMP=$(date --rfc-3339=date)
sed -i "s/^Timestamp: [0-9\-]*/Timestamp: $TIMESTAMP/" $ZYNTHIAN_DIR/build_info.txt

# Delete logs
echo "Deleting system logs ..."
for f in /var/log/* /var/log/**/* ; do
	if [ -f $f ]; then
		cat /dev/null > $f
	fi
done

# Clean history
echo "Cleaning shell history ..."
cat /dev/null > ~/.bash_history && history -c && history -w

#------------------------------------------------------------------------------
# Enable first-boot service => It's already enabled!
#------------------------------------------------------------------------------

#./set_first_boot.sh
