#!/usr/bin/env bash
# Script to build ZynthianOS
# The start Script for this module
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

set -x
alias bash='bash -x'

function systemctl() {
	echo "systemctl trutxo!"
}

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

# Set dpkg interface
export DEBIAN_FRONTEND=noninteractive

#------------------------------------------------------------------------------
# Get System Codebase
#------------------------------------------------------------------------------

ZYNTHIAN_OS_CODEBASE=`lsb_release -cs`

#------------------------------------------------------------------------------
# Load Environment Variables
#------------------------------------------------------------------------------

source "/zynthian/config/zynthian_envars.sh"

#------------------------------------------------------------------------------
# Pull from zynthian-sys repotory ...
#------------------------------------------------------------------------------

echo "Updating zynthian-sys ..."
cd $ZYNTHIAN_SYS_DIR
git checkout .
git pull

#------------------------------------------------------------------------------
# Call update subscripts ...
#------------------------------------------------------------------------------

echo "UPDATING ZYNTHIAN ..."
cd ./scripts
./update_zynthian_recipes.sh
./update_zynthian_data.sh
./update_zynthian_sys.sh
./update_zynthian_code.sh

#------------------------------------------------------------------------------
# Enable first-boot service
#------------------------------------------------------------------------------

#./set_first_boot.sh
