#!/usr/bin/env bash
# Script to build ZynthianOS
# The start Script for this module
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

set -x
alias bash='bash -x'

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

# Update Zynthian
/zynthian/zynthian-sys/scripts/update_zynthian.sh

# Enable first-boot service
systemctl enable first_boot

